IsazaEngTech/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin

from pages.views import ContactView

urlpatterns = [
    url(r'^', include('pages.urls', namespace='pages')),
    url(r'^admin/', admin.site.urls),
]

pages/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ContactView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/index.html'), name='index'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^services/$', TemplateView.as_view(template_name='pages/services.html'), name='services'),
    url(r'^services/advanced-mathematical-modelling/$',
        TemplateView.as_view(template_name='pages/advanced_mathematical_modelling.html'),
        name='services-advanced-mathematical-modelling'),
    url(r'^services/process-engineering/$',
        TemplateView.as_view(template_name='pages/process_engineering.html'),
        name='services-process-engineering'),
    url(r'^services/custom-engineering-software/$',
        TemplateView.as_view(template_name='pages/custom_engineering_software.html'),
        name='services-custom-engineering-software'),
    url(r'^services/computational-modelling/$',
        TemplateView.as_view(template_name='pages/computational_fluid_dynamics.html'),
        name='services-computational-fluid-dynamics'),
    url(r'^contact/$', ContactView.as_view(), name='contact')
]

pages/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

pages/forms.py
from django import forms
from django.core import mail


class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your name'
    }))

    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your e-mail'
    }))

    subject = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter a subject'
    }))

    message = forms.CharField(required=True, max_length=1000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Enter a message'
    }))

    attachments = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={
        'multiple': True
    }))

    def send_email(self):
        mail.EmailMessage(
            subject='Contact: "{}"'.format(self.cleaned_data['subject']),
            body=self.cleaned_data['message'],
            to=['info@isazaengtech.com', 'obrienadam89@gmail.com'],
            from_email='webmaster@isazaengtech.com',
            reply_to=[self.cleaned_data['email']],
            attachments=[(file.name, file.file.read(), file.content_type) for file in self.files.getlist('attachments')]
        ).send()

pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import FormView

from forms import ContactForm

class ContactView(FormView):
    template_name = 'pages/contact.html'
    form_class = ContactForm
    success_url = '/'

    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)

pages/templates/pages/about.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='about' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                At Isaza Eng Tech we provide our clients with consulting services based on advanced engineering
                mathematics. We develop tools that improve the way in which current engineering calculations are
                conducted, by leveraging our background in analytical and computational methods. Our mission is to
                provide clients with platforms that will enable them to meet today’s need for more efficient
                engineering designs, taking their businesses to the next level.
            </p>
        </div>
    </div>
{% endblock %}

pages/templates/pages/advanced_mathematical_modelling.html
{% extends '__base.html' %}
{% load staticfiles %}

{% block navigation %}
    {% include '_navbar.html' with active='services' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Advanced Mathematical Modelling</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                One of our core services includes the advanced mathematical modelling of real-world
                engineering applications. We use a diverse array of techniques to model phenomena including:
            <ol>
                <li class="h4">Heat transfer and thermal systems</li>
                <ul>
                    <li>Moving bed heat exchangers, pebble bed nuclear reactors, double-pipe and
                        shell-and-tube heat exchangers, air coolers, etc.
                    </li>
                    <li>HVAC design and optimization</li>
                    <li>Heat conduction in solids of different geometries</li>
                </ul>
                <li class="h4">Fluid systems</li>
                <ul>
                    <li>Incompressible and compressible pipe flow, aerodynamics and moving
                        boundary problems
                    </li>
                    <li>Network optimization of multicomponent systems (i.e. industrial process
                        modeling)
                    </li>
                    <li>Mutiphase systems – combustion, bitumen extraction, sedimentation, etc.</li>
                </ul>
            </ol>
            </p>

            <h2 class="page-header">Our Advantage</h2>
            <p>
                Our team consists of highly trained engineers with backgrounds in both industry and
                academics. We seek to bridge the gap between novel, abstract ideas in academia and practical
                implementation in industrial settings.
            </p>

            <h2 class="page-header">Analytical Mathematics</h2>
            <p>
                Our team has experience in conducting cutting edge mathematical research in Partial
                Differential Equations (PDEs). We specialize in novel approaches for deriving governing
                equations, such as the volume averaging method. Our mathematical techniques for solving
                these problems include advanced integral transforms, Green’s functions and separation of
                variables. This provides us with a deeper insight into the underlying physics of many
                engineering problems.
            </p>

            <div class="row">
                <div class="col-md-6">
                    <img src="{% static 'pages/img/mbhe-diagram.png' %}" class="img-responsive">
                    <p class="text-center">Schematic of the Moving Bed Heat Exchanger (MBHE).</p>
                </div>
                <div class="col-md-6">
                    <img src="{% static 'pages/img/mbhe-temp-profile.png' %}" class="img-responsive img-portfolio">
                    <p class="text-center">
                        Temperature profile for the MBHE computed using an analytical solution.
                    </p>
                </div>
            </div>

            <h2 class="page-header">Numerical Mathematics</h2>
            <p>
                Our team also has extensive experience in implementing and developing state-of- the-art
                numerical modelling software for solving complex PDEs. Our expertise includes the
                development of Computational Fluid Dynamics (CFD) software using the Finite-Volume Method
                (FVM), numerical optimization, and Finite-Difference methods. We’ve successfully explored
                problems ranging from the combustion of laboratory-scale burners to the dynamics of liquid
                droplets. We also have considerable experience in High Performance Computing (HPC) for
                resource intensive problems.
            </p>
        </div>
    </div>
{% endblock %}

pages/templates/pages/careers.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='careers' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Careers</h1>
        </div>
    </div>
{% endblock %}

pages/templates/pages/computational_fluid_dynamics.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='services' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Computational Fluid Dynamics</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                Computational Fluid Dynamics (CFD) is a rapidly growing field for modelling fluid systems. Significant
                increases in available computing power have enabled engineers to use numerical models to solve complex
                fluid equations. This allows them to model everything from the aerodynamics of vehicles to combustion
                within gas turbine engines. Our team currently focuses our CFD efforts in the modelling of fluid components
                in manufacturing sysytems.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                CFD of Modelling of Fluid System Components
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                Accurately describing/predicting the performance of large fluid systems also requires understanding the
                source of inefficiencies at the component levels. Approximately 20&ndash;30% of all energy in fluid
                systems is consumed by minor losses. Our CFD efforts seek both to reduce the source of these losses by
                making adjustments to the geometries of these components. Additionally, we're using CFD to create a more
                complete description of losses, in order to obtain more reliable results from our flagship node network
                fluid system modeller <a href="{% url 'pages:services-custom-engineering-software' %}">Poiseulle</a>.
            </p>
        </div>
    </div>
{% endblock %}

pages/templates/pages/contact.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='contact' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                Send us a message using the contact form below, or reach us directly at:
            </p>
            <p>
                <strong>E-mail:</strong> <a href="mailto:info@isazaengtech.com?Subject=Inquiry">info@isazaengtech.com</a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="form">
                <form id="contact-form" method="post" enctype="multipart/form-data" action="{% url 'pages:contact' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/pages/custom_engineering_software.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='services' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Custom Engineering Software</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            The complexity of modern engineering projects often warrants the design of highly specialized tools. We
            offer
            software solutions for a number of engineering applications, built in house by our highly trained team of
            engineers with academic and industrial backgrounds. We also offer support and development services, and can
            work with you to build tools to aid in the design and maintenance of engineering systems.
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                Poiseulle - Node Network Flow Optimization
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                Our flagship software product, Poiseulle, allows the user to model complex fluid systems with an
                easy-to-use
                graphical interface. The solver itself is capable of solving flows through arbitrarily connected
                systems.
                It has a variety of built-in models for fluid mechanics, and can easily be extended to accommodate
                customized
                models. Our team is available to consult with users to develop extended models that are tailored to each
                client's individual requirements.
            </p>

            <p>
                Currently, Poiseulle is suitable for:
            <ul>
                <li>Design of pneumatic manufacturing systems</li>
                <li>HVAC design and optimization</li>
                <li>Dust control systems</li>
                <li>Hydraulic systems</li>
            </ul>
            </p>

            <p>
                Additionally, Poiseulle contains a built-in optimizer than can assist in the sizing of fans, pumps,
                valves etc. This ability to quickly construct models of fluid systems and perform optimizations greatly
                reduces the amount of time needed to bring new plants/systems online; and takes a great deal of
                uncertainty out of the design process.
            </p>
        </div>
    </div>
{% endblock %}

pages/templates/pages/index.html
{% extends '__base.html' %}
{% load staticfiles %}

{% block title %}Isaza Eng Tech - Home{% endblock %}

{% block header %}
    <!-- Header Carousel -->
    <header id="carousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill"
                     style="background-image:url('{% static 'pages/img/math_banner-min.png' %}');"></div>
                <div class="carousel-caption">
                    <h2>Advanced Mathematical Modelling</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill"
                     style="background-image:url('{% static 'pages/img/process_modelling_banner.png' %}');"></div>
                <div class="carousel-caption">
                    <h2 class="banner">Process Engineering</h2>
                </div>
            </div>
            <div class="item">
                <!--
                <div class="fill"
                     style="background-image:url('http://cdn.wonderfulengineering.com/wp-content/uploads/2014/04/code-wallpaper-38.jpg');"></div>
                -->
                <div class="fill"
                     style="background-image:url('{% static 'pages/img/custom_software_banner.png' %}');"></div>

                <div class="carousel-caption">
                    <h2 class="banner">Custom Engineering Software</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill"
                     style="background-image:url('https://www.cfd.tu-berlin.de/research/acoustic/JJPF/Jet_DNS_magu_12500_full.png');"></div>
                <div class="carousel-caption">
                    <h2>Computational Fluid Dynamics</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
{% endblock %}

{% block content %}
    <!-- Marketing Icons Section -->

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Advanced Engineering
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-push-4">
            <h3 class="page-header">Advanced Mathematical Modelling</h3>
            <p>
                We offer cutting-edge engineering mathematics consulting. Our team can formulate and solve the governing
                equations behind today’s complex engineering projects.
            </p>
            <a href="{% url 'pages:services-advanced-mathematical-modelling' %}" class="btn btn-primary">Learn More</a>
        </div>
        <div class="col-md-4 text-center col-md-pull-8">
            <a href="{% url 'pages:services-advanced-mathematical-modelling' %}">
                <img src="{% static 'pages/img/math1.png' %}" class="img-responsive img-portfolio">
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <h3 class="page-header">Process Engineering</h3>
            <p>
                We develop process modeling tools, and are familiar with today’s commercial programs. Along with our
                partners, we can take your project from front-end engineering to commissioning and validation.
            </p>
            <a href="{% url 'pages:services-process-engineering' %}" class="btn btn-primary">Learn More</a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'pages:services-process-engineering' %}">
                <img src="{% static 'pages/img/process_modelling_icon.png' %}" class="img-responsive img-portfolio">
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-push-4">
            <h3 class="page-header">Custom Engineering Software</h3>
            <p>
                Our sophisticated in house engineering software can optimize/solve sophisticated networks of
                fluid
                components, as well as model physical phenomena using state-of-the-art numerical methods. We
                also
                offer customized software in order to fit client's needs.
            </p>
            <a href="{% url 'pages:services-custom-engineering-software' %}" class="btn btn-primary">Learn More</a>
        </div>
        <div class="col-md-4 col-md-pull-8">
            <a href="{% url 'pages:services-custom-engineering-software' %}">
                <img src="{% static 'pages/img/custom_engineering_icon.png' %}" class="img-responsive img-portfolio">
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <h3 class="page-header">Computational Fluid Dynamics</h3>
            <p>
                Our experts have developed in house tools for computational modelling, and are also familiar
                in several popular open source and commercial engineering software packages.
            </p>
            <a href="{% url 'pages:services-computational-fluid-dynamics' %}" class="btn btn-primary">Learn More</a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'pages:services-computational-fluid-dynamics' %}">
                <img src="{% static 'pages/img/computational_icon.png' %}" class="img-responsive img-portfolio">
            </a>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <!-- Script to Activate the Carousel -->
    <script type="text/javascript">
        $('.carousel').carousel({
            interval: 5000 //changes the speed
        })
    </script>
{% endblock %}

pages/templates/pages/process_engineering.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='services' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Process Engineering</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>
                Our process engineering team, alongside our partners, can provide you with the competitive
                advantage needed in today’s markets. We have experience in applications ranging from utility
                systems to reactor modeling. The Isaza Eng Tech advantage is our unique background in
                engineering mathematics.
            </p>
            <p>
                Our process team has expertise in areas including:
            <ul>
                <li>Simple and Complex Heat and Mass Balance Development</li>
                <li>Modeling of Compressible and Incompressible Fluid Systems and Networks</li>
                <li>Tank and Pressure Vessel Design</li>
                <li>Heat Transfer Equipment Sizing</li>
                <li>Advanced HVAC Design and Optimization</li>
                <li>Dust Control and Fume Extraction</li>
                <li>Creation of PFDs and P&amp;IDs</li>
                <li>Process Equipment Sizing and Specification</li>
                <li>R&amp;D and Testing Support</li>
                <li>Commissioning and Start-up</li>
            </ul>
            </p>
        </div>
    </div>
{% endblock %}

pages/templates/pages/services.html
{% extends '__base.html' %}

{% block navigation %}
    {% include '_navbar.html' with active='services' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Services</h1>
        </div>
    </div>
{% endblock %}

templates/__base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Isaza Eng Tech website">
    <meta name="author" content="Adam R. O'Brien">

    <title>{% block title %}Isaza Eng Tech{% endblock %}</title>

    {% block css %}
        <!-- Bootstrap Core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">

        <!-- Custom CSS -->
        <link href="{% static "pages/css/modern_business.css" %}" rel="stylesheet">
        <link href="{% static "pages/css/custom.css" %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <!--
        <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        -->

        <script src="https://use.fontawesome.com/bf2970f4ef.js"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}

</head>

<body>

{% block navigation %}
    {% include '_navbar.html' %}
{% endblock %}

{% block header %}{% endblock %}

<!-- Page Content -->
<div class="container">
    {% block content %}{% endblock %}

    {% block footer %}
        <!-- Footer -->
        <hr>
        <footer id="footer" role="contentinfo">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Isaza Eng Tech 2017</p>
                </div>
            </div>
        </footer>
    {% endblock %}
</div>
<!-- /.container -->

{% block js %}
    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
{% endblock %}

</body>

</html>

templates/_navbar.html
{% load staticfiles %}

<!-- Navigation -->
<nav class="navbar navbar-static-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'pages:index' %}">
                <img src="{% static "pages/img/isaza_eng_tech_icon.png" %}" class="img-responsive" alt="Isaza Eng Tech">
            </a>

            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#responsive-navbar" aria-controls="">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="responsive-navbar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'pages:about' %}" id="nav-about"
                       {% if active == 'about' %}class="active"{% endif %}>About</a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle{% if active == 'services' %} active{% endif %}" data-toggle="dropdown"
                       href="#">Services +</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'pages:services-advanced-mathematical-modelling' %}">Advanced Mathematical
                            Modelling</a></li>
                        <li><a href="{% url 'pages:services-process-engineering' %}">Process Engineering</a></li>
                        <li><a href="{% url 'pages:services-custom-engineering-software' %}">Custom Engineering
                            Software</a></li>
                        <li><a href="{% url 'pages:services-computational-fluid-dynamics' %}">Computational Fluid
                            Dynamics</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'pages:contact' %}" id="nav-contact"
                       {% if active == 'contact' %}class="active"{% endif %}>Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>